### ISSUE TITLE
Sudo required?

### ISSUE THREAD

**Issue by d4ncer** [flipace/whoport#2]
Any reason sudo is required for the lookup?

**Comment by flipace** [comment]
If you invoke the lsof command without sudo, you'll only get processes for the current user. In my case at least my processes run under different users and thats why I added sudo as default to the command. I could remove it and using `sudo whoport 80` would yield the same result, but if a process listening on port 80 is run by a different or root user and you dontuse whoport with sudo, you'd just get "no processes found". 

What do you think, should i remove it and just add some more information to the readme (and command help)?

**Comment by d4ncer** [comment]
That's fair. My concern is being prompted to enter my password when using a third party CLI tool caused me to pause and re-evaluate if I really needed the tool in the first place. 

Your point is valid, though. Maybe remove it from the CLI itself, and add a section to the README that points out the difference between `whoport 80` and `sudo whoport 80`

**Comment by flipace** [comment]
done!
