### ISSUE TITLE
Node path issue on Debian

### ISSUE THREAD

**Issue by BonneVoyager** [flipace/whoport#3]
Hi,

I tried to run **whoport** on Debian 8  (jessie) and got:

> /usr/bin/env: node --harmony: No such file or directory

Then I tried **which node** and got:

> /opt/nodejs/bin/node

Basically, Node.js path is not recognised properly.

Thanks

**Comment by flipace** [comment]
hey @BonneVoyager, this should work now in v0.1.2 it seems like the harmony flag is not supported the way i used it in some distributions.

**Comment by BonneVoyager** [comment]
Works like a charm (tested on recent Ubuntu, Debian and CentOS).
